-- MySQL Script generated by MySQL Workbench
-- 07/31/16 13:03:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ccde_wx_push
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ccde_wx_push
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ccde_wx_push` DEFAULT CHARACTER SET utf8 ;
USE `ccde_wx_push` ;

-- -----------------------------------------------------
-- Table `ccde_wx_push`.`app`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ccde_wx_push`.`app` (
  `app_id` INT NOT NULL,
  `app_name` VARCHAR(128) NOT NULL,
  `app_server_ip` VARCHAR(16) NOT NULL,
  `app_wx_id` INT NOT NULL,
  `app_wx_corp_id` VARCHAR(128) NOT NULL,
  `app_wx_corp_secret` VARCHAR(128) NOT NULL,
  `app_channel` VARCHAR(128) NOT NULL,
  `app_create_date` DATE NULL,
  `app_principal_name` VARCHAR(128) NULL,
  `app_principal_phone` VARCHAR(128) NULL,
  `app_principal_email` VARCHAR(128) NULL,
  `app_note` TEXT NULL,
  `app_default_touser` TEXT NULL,
  `app_default_toparty` TEXT NULL,
  `app_default_totag` TEXT NULL,
  `app_switch_flag` TINYINT(1) NOT NULL DEFAULT 0,
  `app_web_login_name` VARCHAR(128) NULL,
  `app_web_login_pass` VARCHAR(128) NULL,
  PRIMARY KEY (`app_id`),
  UNIQUE INDEX `app_web_login_name_UNIQUE` (`app_web_login_name` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `ccde_wx_push`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ccde_wx_push`.`log` (
  `log_id` INT NOT NULL AUTO_INCREMENT,
  `log_push_touser` TEXT NULL,
  `log_push_toparty` TEXT NULL,
  `log_push_totag` TEXT NULL,
  `log_push_text` TEXT NOT NULL,
  `log_push_ret` TEXT NOT NULL,
  `log_insert_time` DATETIME NULL,
  `log_push_time` DATETIME NULL,
  `log_push_success_status` TINYINT(1) NOT NULL DEFAULT 0,
  `app_id` INT NOT NULL,
  PRIMARY KEY (`log_id`),
  INDEX `fk_log_app_idx` (`app_id` ASC))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
